name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: installing dependencies
      run: npm install
    - name: run unit tests
      run: npm run test:unit
    - name: display SoftUni username
      run: echo "Murtadoc"
    
  ui_test:
    needs: build_test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: installing dependencies
      run: npm install
    - name: install playwright dependencies
      run: npx playwright install
    - name: start the app
      run: npm start &
    - name: run UI tests
      run: npm run test:ui     